In [ ]:
! wget https://data.virginia.gov/dataset/de833a43-7019-444c-8384-9e0cf5255140/resource/60506bbb-685f-4360-8a8c-30e137ce3615/download/community-policing-data.csv

--2025-04-01 00:15:13--  https://data.virginia.gov/dataset/de833a43-7019-444c-8384-9e0cf5255140/resource/60506bbb-685f-4360-8a8c-30e137ce3615/download/community-policing-data.csv
Resolving data.virginia.gov (data.virginia.gov)... 104.19.219.112, 104.19.218.112, 2606:4700::6813:da70, ...
Connecting to data.virginia.gov (data.virginia.gov)|104.19.219.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://s3.amazonaws.com:443/og-production-open-data-shared-ckan-892364687672/odgava/resources/60506bbb-685f-4360-8a8c-30e137ce3615/community-policing-data.csv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJJIENTAPKHZMIPXQ%2F20250401%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250401T001513Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=a41ab9485612fa7f26ef1ffcf2fa1ff1585e5549185083f67501e20fbd8885c7 [following]
--2025-04-01 00:15:13--  https://s3.amazonaws.com/og-production-open-data-shared-ckan-892364687672/odgava/resources/60506bbb-6

In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv("community-policing-data.csv", on_bad_lines="skip")
display(data)

C:\Users\sophi\AppData\Local\Temp\ipykernel_16528\2344752088.py:1: DtypeWarning: Columns (13,16) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("community-policing-data.csv", on_bad_lines="skip")


STOP_DATE                AGENCY NAME  \
0        12/28/2022             VSP Division 7   
1        12/28/2022             VSP Division 7   
2        12/28/2022             VSP Division 7   
3        12/28/2022             VSP Division 7   
4        12/28/2022             VSP Division 7   
...             ...                        ...   
4311288   1/13/2024  Henrico Police Department   
4311289   1/13/2024  Henrico Police Department   
4311290   1/13/2024  Henrico Police Department   
4311291   1/13/2024  Henrico Police Department   
4311292   1/13/2024  Henrico Police Department   

                                 LOCATION             JURISDICTION  \
0          EB 66 AT EXIT 44 RT 234 BYPASS  Prince William CO (076)   
1        OLD BRIDGE RD/PRINCE WILLIAM PKW  Prince William CO (076)   
2          WB 267 AT EXIT 5 CLAIBORNE PKW         Loudoun CO (053)   
3                NB 95 AT EXIT 169 RT 644         Fairfax CO (029)   
4           SB 495 AT BRADDOCK RD EXIT 54         Fairfax CO (029)   
...                                   ...                      ...   
4311288                  6900  FOREST AVE         Henrico CO (043)   
4311289                     3300  PUMP RD         Henrico CO (043)   
4311290                  7700 E PARHAM RD         Henrico CO (043)   
4311291        KENWOOD AVE & HERMITAGE RD         Henrico CO (043)   
4311292                6100  LAKESIDE AVE         Henrico CO (043)   

                       REASON FOR STOP       PERSON TYPE  \
0                  Equipment Violation            Driver   
1                    Traffic Violation            Driver   
2        Other Investigative Detention  Other Individual   
3                    Traffic Violation            Driver   
4                    Traffic Violation            Driver   
...                                ...               ...   
4311288              Calls for Service  Other Individual   
4311289              Traffic Violation            Driver   
4311290              Calls for Service  Other Individual   
4311291              Traffic Violation            Driver   
4311292              Traffic Violation            Driver   

                              RACE               ETHNICITY      AGE  GENDER  \
0                            White  Non-Hispanic or Latino       22    Male   
1                            White  Non-Hispanic or Latino       34    Male   
2                            White  Non-Hispanic or Latino  Unknown    Male   
3        Black or African American  Non-Hispanic or Latino       29  Female   
4        Black or African American  Non-Hispanic or Latino       20    Male   
...                            ...                     ...      ...     ...   
4311288                      White      Hispanic or Latino       37    Male   
4311289                      White  Non-Hispanic or Latino       30  Female   
4311290  Black or African American  Non-Hispanic or Latino       41    Male   
4311291                      White  Non-Hispanic or Latino       46  Female   
4311292                      White  Non-Hispanic or Latino       30    Male   

         ...      ACTION TAKEN SPECIFIC VIOLATION VIRGINIA CRIME CODE  \
0        ...    Warning Issued           46.2-646                 NaN   
1        ...  Citation/Summons           46.2-646                 NaN   
2        ...    Warning Issued           46.2-928                 NaN   
3        ...  Citation/Summons           46.2-646                 NaN   
4        ...  Citation/Summons         46.2-818.2                 NaN   
...      ...               ...                ...                 ...   
4311288  ...  Citation/Summons           18.2-103                 NaN   
4311289  ...  Citation/Summons     46.2-613(A)(1)                 NaN   
4311290  ...            Arrest           18.2-388                 NaN   
4311291  ...  Citation/Summons           46.2-878                 NaN   
4311292  ...  Citation/Summons           46.2-878                 NaN   

        PERSON SEARCH

In [3]:
terry_stops = data[data["REASON FOR STOP"] == "Terry Stop"]
display(terry_stops)

STOP_DATE                   AGENCY NAME  \
886      10/26/2022                VSP Division 7   
1332     11/16/2022                VSP Division 7   
1402     11/15/2022                VSP Division 7   
1650       9/5/2023  Waynesboro Police Department   
1658      9/25/2023  Waynesboro Police Department   
...             ...                           ...   
4310413    1/3/2024     Henrico Police Department   
4310594   1/15/2024     Henrico Police Department   
4310599   1/15/2024     Henrico Police Department   
4311089   1/11/2024     Henrico Police Department   
4311090   1/11/2024     Henrico Police Department   

                                   LOCATION             JURISDICTION  \
886                               66/RT 286         Fairfax CO (029)   
1332     SB 395 AT BOUNDRY CHNL DR EXIT 10A       Arlington CO (000)   
1402                  RT 1/QUANTICO GATEWAY  Prince William CO (076)   
1650                     700 S MAGNOLIA AVE         Waynesboro (127)   
1658                         1200 W MAIN ST         Waynesboro (127)   
...                                     ...                      ...   
4310413        ALMA AVE  AT E  LABURNUM AVE         Henrico CO (043)   
4310594      5500  WILLIAMSBURG RD  Apt 322         Henrico CO (043)   
4310599       GASKINS RD  AT THREE CHOPT RD         Henrico CO (043)   
4311089   5100 OLD MAIN ST HENRICO VA 23231         Henrico CO (043)   
4311090   5100 OLD MAIN ST HENRICO VA 23231         Henrico CO (043)   

        REASON FOR STOP       PERSON TYPE                       RACE  \
886          Terry Stop  Other Individual                      White   
1332         Terry Stop  Other Individual  Black or African American   
1402         Terry Stop            Driver  Black or African American   
1650         Terry Stop            Driver                      White   
1658         Terry Stop            Driver                      White   
...                 ...               ...                        ...   
4310413      Terry Stop  Other Individual                    Unknown   
4310594      Terry Stop  Other Individual  Black or African American   
4310599      Terry Stop  Other Individual                      White   
4311089      Terry Stop  Other Individual  Black or African American   
4311090      Terry Stop  Other Individual  Black or African American   

                      ETHNICITY      AGE  GENDER  ...           ACTION TAKEN  \
886                     Unknown       50    Male  ...  No Enforcement Action   
1332     Non-Hispanic or Latino       62    Male  ...  No Enforcement Action   
1402     Non-Hispanic or Latino       38  Female  ...       Citation/Summons   
1650     Non-Hispanic or Latino       19    Male  ...         Warning Issued   
1658                    Unknown       61    Male  ...       Citation/Summons   
...                         ...      ...     ...  ...                    ...   
4310413                 Unknown  Unknown   Other  ...  No Enforcement Action   
4310594  Non-Hispanic or Latino       35  Female  ...                 Arrest   
4310599  Non-Hispanic or Latino       76  Female  ...  No Enforcement Action   
4311089  Non-Hispanic or Latino       19  Female  ...         Warning Issued   
4311090  Non-Hispanic or Latino       21    Male  ...         Warning Issued   

        SPECIFIC VIOLATION VIRGINIA CRIME CODE PERSON SEARCHED  \
886               46.2-928                 NaN               N   
1332                   NaN                 NaN               N   
1402              46.2-888                 NaN               N   
1650              18.2-119                 NaN               N   
1658              46.2-878                 NaN               N   
...                    ...                 ...             ...   
4310413                NaN                 NaN               N   
4310594          19.2-82.1                 NaN               N   
4310599                NaN                 NaN               N   
4311089           18.2

In [4]:
for column in terry_stops.columns:
    print(f"Value counts for {column}:")
    print(terry_stops[column].value_counts(dropna=False))
    print()

Value counts for STOP_DATE:
STOP_DATE
4/30/2022     68
7/22/2021     63
9/3/2021      57
9/1/2022      56
9/3/2022      56
              ..
2/15/2021      1
11/19/2023     1
12/3/2023      1
12/4/2023      1
12/1/2023      1
Name: count, Length: 1597, dtype: int64

Value counts for AGENCY NAME:
AGENCY NAME
Fairfax County Police Department                9163
Virginia Beach Police Department                1963
Henrico Police Department                       1901
Norfolk Police Department                       1447
Chesterfield County Police Department           1221
                                                ... 
Arlington County Sheriff's Office                  1
Germanna Community College Police Department       1
Lynchburg City Sheriff's Office                    1
Honaker Police Department                          1
Pearisburg Police Department                       1
Name: count, Length: 268, dtype: int64

Value counts for LOCATION:
LOCATION
SOUTH COUNTY DRIVE AT WEST MAIN S

In [5]:
# replace - with NaN
feature_list = ["FORCE USED BY SUBJECT", "FORCE USED BY OFFICER", "VEHICLE SEARCHED", "PERSON SEARCHED", "ENGLISH SPEAKING"]
for feature in feature_list:
  terry_stops[feature].replace('-', np.nan, inplace= True)


C:\Users\sophi\AppData\Local\Temp\ipykernel_16528\3029540058.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  terry_stops[feature].replace('-', np.nan, inplace= True)
C:\Users\sophi\AppData\Local\Temp\ipykernel_16528\3029540058.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  terry_stops[feature].replace('-', np.nan, inplace= True)


In [6]:
for column in terry_stops.columns:
    print(f"Value counts for {column}:")
    print(terry_stops[column].value_counts(dropna=False))
    print()

Value counts for STOP_DATE:
STOP_DATE
4/30/2022     68
7/22/2021     63
9/3/2021      57
9/1/2022      56
9/3/2022      56
              ..
2/15/2021      1
11/19/2023     1
12/3/2023      1
12/4/2023      1
12/1/2023      1
Name: count, Length: 1597, dtype: int64

Value counts for AGENCY NAME:
AGENCY NAME
Fairfax County Police Department                9163
Virginia Beach Police Department                1963
Henrico Police Department                       1901
Norfolk Police Department                       1447
Chesterfield County Police Department           1221
                                                ... 
Arlington County Sheriff's Office                  1
Germanna Community College Police Department       1
Lynchburg City Sheriff's Office                    1
Honaker Police Department                          1
Pearisburg Police Department                       1
Name: count, Length: 268, dtype: int64

Value counts for LOCATION:
LOCATION
SOUTH COUNTY DRIVE AT WEST MAIN S

In [7]:
terry_stops.info()


<class 'pandas.core.frame.DataFrame'>
Index: 35296 entries, 886 to 4311090
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   STOP_DATE              35296 non-null  object 
 1   AGENCY NAME            35296 non-null  object 
 2   LOCATION               35234 non-null  object 
 3   JURISDICTION           35296 non-null  object 
 4   REASON FOR STOP        35296 non-null  object 
 5   PERSON TYPE            35296 non-null  object 
 6   RACE                   35296 non-null  object 
 7   ETHNICITY              35296 non-null  object 
 8   AGE                    35296 non-null  object 
 9   GENDER                 35296 non-null  object 
 10  ENGLISH SPEAKING       30857 non-null  object 
 11  ACTION TAKEN           35296 non-null  object 
 12  SPECIFIC VIOLATION     26866 non-null  object 
 13  VIRGINIA CRIME CODE    0 non-null      object 
 14  PERSON SEARCHED        35282 non-null  object 
 15  VEH

In [8]:
# removing all the columns with all null values
terry_stops = terry_stops.drop(columns = ["VIOLATION TYPE", "ADDITIONAL ARREST", "VIRGINIA CRIME CODE"])

# the features without null values are:
# stop date, agency name, jurisdiction, reason for stop, person type, race, ethnicity, age, gender, action taken, residency

In [9]:
terry_stops.describe()

STOP_DATE                       AGENCY NAME  \
count       35296                             35296   
unique       1597                               268   
top     4/30/2022  Fairfax County Police Department   
freq           68                              9163   

                                      LOCATION      JURISDICTION  \
count                                    35234             35296   
unique                                   22159               133   
top     SOUTH COUNTY DRIVE AT WEST MAIN STREET  Fairfax CO (029)   
freq                                       366              9488   

       REASON FOR STOP PERSON TYPE   RACE               ETHNICITY    AGE  \
count            35296       35296  35296                   35296  35296   
unique               1           4      6                       3     97   
top         Terry Stop      Driver  White  Non-Hispanic or Latino     19   
freq             35296       15885  21125                   26939   1632   

       GENDER ENGLISH SPEAKING           ACTION TAKEN SPECIFIC VIOLATION  \
count   35296            30857                  35296              26866   
unique      5                2                      5               1159   
top      Male                Y  No Enforcement Action           18.2-119   
freq    25922            28191                  10248               3060   

       PERSON SEARCHED VEHICLE SEARCHED FORCE USED BY OFFICER  \
count            35282            34782                 30858   
unique               2                2                     2   
top                  N                N                     N   
freq             26650            32314                 30395   

       FORCE USED BY SUBJECT                        RESIDENCY  
count                  30859                            35296  
unique                     2                                5  
top                        N  Resident of city/county of stop  
freq                   30553                            14126

In [10]:
# I am going to remove reason for stop because they are all the same
terry_stops = terry_stops.drop(columns = ["REASON FOR STOP"])

# I am going to remove this for the clustering because it is not helpful
# We can later do it by month or year if we are intrested but not for now
terry_stops = terry_stops.drop(columns = ["STOP_DATE"])


# I am dropping these because I think jurisdiction cover the same info, but its less grandular so might led to fewer generalizations
terry_stops = terry_stops.drop(columns = ["AGENCY NAME",	"LOCATION"])

In [11]:
terry_stops["SPECIFIC VIOLATION"].value_counts()
# All of this is from https://law.lis.virginia.gov/vacode/
# Most common is "Trespass after having been forbidden to do so; penalties"
# Second most common is "Maximum speed limits generally"
# Thirs most common is "Possession of controlled substances unlawful" --> I think this might be the best to look into

SPECIFIC VIOLATION
18.2-119          3060
46.2-870          1300
18.2-250(A)(A)    1075
46.2-301           858
18.2-388           847
                  ... 
15.2-926(B)          1
18.2-57.02           1
5-JUN                1
18-JUN               1
4.1-305.1            1
Name: count, Length: 1159, dtype: int64

In [31]:

train_set, test_set = train_test_split(terry_stops, test_size=0.2, random_state=42)

# Change with what you want to predict
predict = "ACTION TAKEN"
X_train = train_set.drop(predict, axis=1)
y_train = train_set[predict].copy()

X_test = test_set.drop(predict, axis=1)
y_test = test_set[predict].copy()

In [32]:
num_pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy="median")),
        ('std_scaler', StandardScaler())
    ])


num_attribs = list(X_train.select_dtypes(include=[np.number]))
# These are the categorical values that I thought would be most useful
cat_few = ["PERSON TYPE","RACE","ETHNICITY", "GENDER", "RESIDENCY"]
cat_alot = ["PERSON SEARCHED","VEHICLE SEARCHED",	"FORCE USED BY OFFICER",	"FORCE USED BY SUBJECT", "ENGLISH SPEAKING","JURISDICTION" ]
encoder = LabelEncoder()

full_pipeline = ColumnTransformer([
        ("num", num_pipeline, num_attribs),
        ("cat_few", OneHotEncoder(handle_unknown='ignore'), cat_few),
        ("cat_alot", OrdinalEncoder(), cat_alot)
    ])

X_train = full_pipeline.fit_transform(X_train)
X_test = full_pipeline.transform(X_test)
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(28236, 28)
(7060, 28)
(28236,)
(7060,)


In [33]:
print(X_train)

[[ 0.  0.  1. ...  0.  1. 58.]
 [ 0.  0.  1. ...  0.  0. 37.]
 [ 1.  0.  0. ...  0.  1. 58.]
 ...
 [ 1.  0.  0. ...  0.  1. 73.]
 [ 0.  0.  1. ...  0.  1. 37.]
 [ 1.  0.  0. ...  0.  1.  1.]]


## Clustering

In [ ]:
from sklearn.cluster import Kmeans
